version: '3.8'

services:
  app:
    build: .
    container_name: webrtc_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./server.js:/usr/src/app/server.js
      - ./public:/usr/src/app/public
    networks:
      - webrtc_network

  nginx:
    image: nginx:alpine
    container_name: webrtc_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - webrtc_network

networks:
  webrtc_network:
    driver: bridge