version: '3.8'

services:
  app:
    build: .
    container_name: webrtc_app
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./public:/usr/src/app/public
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: webrtc_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app